# http://travis-ci.org/#!/ipython/ipython
language: python

cache:
    directories:
        - $HOME/.cache/bower
python:
    - 3.5
    - 2.7

sudo: false

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/pandoc:$PATH
  matrix:
    - GROUP=docs

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools wheel nose coverage codecov
    - nvm install 5.6
    - nvm use 5.6
    - npm upgrade -g npm
    - npm install
    - 'if [[ $GROUP == js* ]]; then  npm install -g casperjs@1.1.0-beta5; fi'
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels

install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=notebook[test]

script:
    - 'if [[ $GROUP == docs ]]; then cd docs && sphinx-build -W -b html -d {envtmpdir}/doctrees docs docs/_build/html; fi'

matrix:
    include:
        - python: 3.3
          env: GROUP=python
        - python: 3.4
          env: GROUP=python

after_success:
    - codecov
