name: notebook_docs
dependencies:
- sphinx>=1.3
- sphinx_rtd_theme
- jinja2
- tornado
- nbformat
- jupyter_client
- ipykernel
- pip:
    - sphinxcontrib_spelling
    - pyenchant
    - recommonmark==0.4.0
